// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://liorbzcsebltevjpcnwt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imxpb3JiemNzZWJsdGV2anBjbnd0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTYxNzk1NjIsImV4cCI6MjA3MTc1NTU2Mn0.tiL2DCmZ5Ytz22MsVNtLeyLqlPCxbSdNgSfwc_BKHkA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});